name = "kzkn My Blank"
license = "MIT"
licenselink = "https://github.com/kzkn/myblank/blob/master/LICENSE.md"
description = "Layout of kazkn.com"
homepage = "https://github.com/kzkn/myblank"
tags = ["blog", "plain", "blank", "starter"]
features = ["blog"]
min_version = 0.17

[author]
  name = "kzkn"
  homepage = "https://github.com/kzkn"
